# Workflow for deploying Docsify content to GitHub Pages
name: Deploy Docsify Site to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions for GITHUB_TOKEN to enable deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping queued runs in between
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout
        uses: actions/checkout@v4

      # Step 2: Setup GitHub Pages
      - name: Setup Pages
        uses: actions/configure-pages@v5

      # Step 3: Upload the Docsify site files (docs directory)
      - name: Upload Docsify Site
        uses: actions/upload-pages-artifact@v3
        with:
          # Only include the `docs/` directory
          path: docs

      # Step 4: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
